#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 145
#define YY_END_OF_BUFFER 146
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[445] =
    {   0,
        0,    0,    0,    0,  146,  144,    2,    3,    3,  115,
      144,  143,  126,  128,  144,  120,  121,  124,  122,  137,
      123,  136,  125,   76,   76,  139,  138,  134,  132,  133,
      114,  135,   67,  118,  119,  127,   65,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,  116,  129,  117,  143,    8,
        8,  125,    9,    2,    3,    3,    3,   95,    0,   70,
        0,  103,  105,    0,    0,   90,  101,   84,   86,   98,
       80,   88,   99,  100,   82,  111,  110,  109,  112,  113,
        0,    4,  102,   74,   76,    0,    0,    0,    0,    0,

       73,    0,  140,  141,  130,   97,   94,  142,   96,  131,
       67,  104,   68,   67,   67,   13,   67,    0,    0,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   33,
       67,   35,   67,   36,   37,   67,   67,   67,   67,   67,
       67,   45,   67,   67,   67,    0,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,  106,   93,    1,    0,
        8,    8,    7,    8,    0,    0,    0,   69,    0,    0,
       89,   83,   85,   79,   87,   81,  108,  107,    0,    0,
        4,   74,    0,    0,   73,   76,    0,    0,   75,    0,
       76,    0,   76,    0,    0,    0,    0,    0,    0,   76,

        0,    0,    0,    0,   76,    0,   91,   78,   92,   67,
       11,   12,   14,   67,   67,    0,   72,    0,    0,    0,
       67,   67,   67,   67,   67,   67,   24,   67,   67,   67,
       67,   67,   67,   34,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   49,   66,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
        1,    8,    0,    0,    0,    0,    0,    0,    0,    5,
       74,    0,   74,    0,    0,    0,   76,   75,    0,   76,
       76,   75,    0,    0,    0,    0,   77,   67,   67,   67,
        0,   71,    0,   67,   67,   20,   67,   67,   67,   67,

       26,   27,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   41,   67,   43,   67,   67,   67,   48,   66,   67,
       52,   67,   67,   56,   67,   57,   58,   67,   67,   67,
       67,   67,    0,    6,    0,    0,    0,    0,   74,   74,
        0,    0,    0,    0,   10,   15,   16,    0,    0,   17,
       18,   67,   67,   22,   67,   25,   67,   29,   67,   67,
       32,   67,   67,   67,   40,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   60,   67,   67,   64,    0,
        0,    0,    0,    0,   75,   67,   67,   67,   67,   30,
       31,   39,   38,   67,   67,   44,   46,   67,   50,   53,

       55,   67,   59,   67,   67,   67,    0,    0,   21,   67,
       67,   67,   67,   67,   47,   67,   67,   67,   63,    0,
        0,   19,   23,   28,   67,   42,   67,   67,   67,    0,
        0,   67,   67,   61,   67,    0,    0,   67,   67,   67,
       51,   54,   62,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   25,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   36,   36,   38,   36,
       39,   39,   39,   39,   39,   39,   39,   39,   40,   39,
       39,   39,   39,   39,   39,   39,   39,   41,   39,   39,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   39,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        5,    1,    1,    1,    6,    1,    6,    1,    1,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    1,
        1,    1,    1,    1,    1,    8,    8,    9,   10,   10,
       10,    1,    1,    1,    1,   11,    8,    8,    8,    8,
        9,   12,   10,   10,   13,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   14,   10,   10,   10,   10,
       10,    1,    1,   15
    } ;

static const flex_int16_t yy_base[483] =
    {   0,
        0, 1004,   72,   73, 1011, 1013,   78,   80,   81,  978,
       72, 1013,  977,  976,  964, 1013, 1013,   78,   79, 1013,
       80,   82,   76,  137,   77,   69, 1013,   73,   74,   87,
     1013, 1013,    0, 1013, 1013,  974,    0,   64,   86,   62,
       65,   70,   83,   86,  950,   79,   74,  105,  124,  133,
      114,  142,  945,  956,  948, 1013,   99, 1013,  995,  196,
      205,  162, 1013,  178,  199,  208,  211, 1013,  179, 1013,
      212, 1013, 1013,  989,  217,  967, 1013,  966,  965, 1013,
      964,  962, 1013, 1013,  961, 1013, 1013,  138, 1013, 1013,
      977,    0, 1013,  179,    0,  127,  203,  218,  944,  203,

      224,  231, 1013, 1013,  163, 1013, 1013, 1013, 1013,  953,
        0, 1013,    0,  929,  183,  198,  935,  184,  938,  925,
      910,  215,  921,  913,  903,  900,  901,  160,  906,    0,
      895,    0,  896,  891,    0,  895,  884,  893,  883,  888,
      893,  888,  888,  876,  883,    0,  865,  870,  864,  202,
      859,  855,  858,  234,  855,  858, 1013, 1013,    0,  244,
      264,  282, 1013,  288,  898,  356,  838, 1013,  898,  817,
     1013, 1013, 1013, 1013, 1013, 1013, 1013, 1013,  874,  280,
        0,  258,  283,  236, 1013,  281,  284,  318,  251,  328,
      345,  392,  253,  838,  857,  854,  285,  855,  835, 1013,

      803,  290,  831,  828, 1013,  766, 1013,  782, 1013,  760,
        0,    0,    0,  753,  754,  314, 1013,  416,  797,  378,
      760,  752,  748,  720,  250,  729,    0,  725,  690,  272,
      687,  690,  663,    0,  666,  674,  668,  661,  642,  649,
      642,  636,  636,  636,  641,    0,    0,  611,  626,  566,
      567,  565,  578,  564,  555,  554,  544,  552,  547,  544,
        0,  320,  586,  312,    0,    0,  588,    0,  581, 1013,
      282,  428,  306,  440,  572,  569,  376,  320,  364,  467,
      262, 1013,  565,  520,  563,  518, 1013,  514,  523,  506,
      527, 1013,  558,  512,  513,    0,  344,  501,  507,  498,

        0,    0,  509,  496,  495,  494,  505,  483,  482,  480,
      489,    0,  477,    0,  475,  476,  492,    0,    0,  475,
        0,  488,  476,    0,  488,    0,  472,  479,  471,  482,
      481,  476,  512, 1013,  451,  450,  509,  406,  374, 1013,
      499,  496,  468,  467,    0,    0,    0,    0,  506,    0,
        0,  465,  460,    0,  455,    0,  460,    0,  446,  451,
        0,  444,  443,  456,    0,  440,  454,  453,  450,  443,
      436,  437,  449,  446,  442,    0,  447,  436,    0,  480,
      414,  410,  560,  409, 1013,  413,  422,  412,  426,    0,
        0,    0,    0,  427,  410,    0,    0,  421,    0,    0,

        0,  414,    0,  411,  415,  393,  383,  372,    0,  394,
      393,  377,  374,  376,    0,  374,  381,  383,    0,  350,
      336,    0,    0,    0,  347,    0,  346,  338,  338,  299,
      286,  299,  288,    0,  267,  198,  189,  176,  110,   48,
        0,    0,    0, 1013,  612,  627,  636,  644,  658,  673,
      682,  690,  695,  707,  722,  730,  744,  759,  770,  782,
      791,  799,  804,  811,  819,  833,  842,  848,  860,  869,
      878,  890,  899,  908,  917,  926,  935,  944,  953,  962,
      971,  980
    } ;

static const flex_int16_t yy_def[483] =
    {   0,
      444,    1,    1,    1,  444,  444,  444,  444,  444,  444,
      445,  444,  444,  444,  446,  444,  444,  444,  444,  444,
      444,  444,  444,  444,   24,  444,  444,  444,  444,  444,
      444,  444,  447,  444,  444,  444,  448,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  445,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      449,  450,  444,  451,   25,  444,  452,  444,  453,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      447,  444,  448,  447,  447,  447,  447,  454,  455,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  456,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  444,  444,  457,  444,
      444,  444,  444,  444,  458,  445,  444,  444,  459,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  449,  460,
      450,  461,  462,  444,  444,  444,  444,  444,  463,  444,
      444,  444,  464,  453,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  447,
      447,  447,  447,  447,  447,  454,  444,  444,  444,  444,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  465,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      457,  444,  458,  466,  166,  467,  459,  468,  469,  444,
      461,  444,  470,  444,  444,  444,  444,  463,  444,  444,
      464,  444,  444,  444,  444,  444,  444,  447,  447,  447,
      454,  444,  471,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  465,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  472,  444,  473,  474,  469,  460,  470,  444,
      444,  444,  444,  444,  447,  447,  447,  291,  471,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  472,
      466,  475,  166,  476,  444,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  477,  478,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  479,
      480,  447,  447,  447,  447,  447,  447,  447,  447,  481,
      482,  447,  447,  447,  447,  444,  444,  447,  447,  447,
      447,  447,  447,    0,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444
    } ;

static const flex_int16_t yy_nxt[1088] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   25,   25,   25,   25,   25,   25,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   33,   33,   33,   33,
       33,   34,    6,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   33,   33,   44,   33,   45,   46,   47,   48,
       49,   33,   50,   51,   52,   53,   54,   55,   33,   33,
       33,   56,   57,   58,   60,   60,   61,   61,   70,   64,
       59,   64,   65,   67,   66,   66,   76,   79,   82,   91,
       62,   62,  118,   86,   92,   87,  119,  103,  443,   88,

      104,   63,   63,  105,  106,  107,  108,   93,  121,   77,
       80,   83,   84,  444,   71,  123,  444,  444,  109,  110,
      114,  122,  115,   89,  444,  137,  125,  116,  126,  129,
      157,  117,  127,  139,  124,  138,  444,  132,  128,  140,
      146,  130,  131,  133,  134,  444,  186,  186,  120,  135,
       78,   81,   85,   90,   94,  177,   95,   95,   95,   95,
       95,   95,   95,   95,   95,  141,  442,  142,  148,  178,
      143,  158,  187,   96,   97,  165,   98,   99,  149,   64,
       92,   64,   95,  147,   96,   70,  144,   97,  100,  145,
      217,  101,  150,   93,  207,  151,   98,  160,  161,  160,

      162,   65,  102,   66,  152,   99,  160,  164,  160,  162,
       67,  153,   66,   65,   69,   66,  183,  188,  166,  188,
      231,   71,  166,  169,  232,  195,  218,  169,  196,  183,
      184,  166,  211,  185,  441,  208,  169,  191,  191,  191,
      191,  191,  191,  191,  197,  160,  198,  160,  190,  199,
      200,  202,  212,  203,  166,  213,  204,  205,  275,  169,
      251,  276,   74,  192,  223,  252,  161,  214,  162,  163,
      166,  383,  224,  225,  166,  169,  166,  167,  163,  169,
      166,  169,  170,  256,  262,  169,  162,  201,  257,  160,
      161,  160,  162,  180,  206,  183,  258,  272,  270,  272,

      277,  277,  279,  186,  186,  185,  283,  101,  183,  184,
      200,  285,  185,  298,  299,  205,  101,  163,  102,  183,
      217,  303,  161,  440,  162,  264,  277,  102,  274,  187,
      334,  304,  183,  184,  439,  101,  185,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  102,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  218,  184,  438,   74,
      185,  163,   70,  190,  280,  280,  280,  280,  280,  280,
      280,  279,  383,  190,  185,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  293,  435,  341,  434,  293,  342,
      280,  265,  265,  265,  433,  277,  277,  293,   71,  101,

      352,  432,  265,  265,  265,  265,  265,  265,  353,   74,
      102,  191,  191,  191,  191,  191,  191,  191,  216,  338,
      293,  277,  291,  383,  270,  184,  291,  381,  185,  429,
      101,  428,  334,  427,  426,  291,  293,  192,  425,  424,
      293,  102,  293,  423,  422,   74,  293,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  383,  419,  291,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  418,  417,
      416,  415,  414,  274,  291,  413,  412,  411,  291,  410,
      291,  409,   74,  383,  291,  274,  280,  280,  280,  280,
      280,  280,  280,  381,  406,  405,  404,  403,  402,  401,

      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,
      390,  389,  280,  388,  387,  386,  292,  205,  200,  385,
      385,  101,  338,   74,  383,  381,  379,  378,  377,  376,
      375,  374,  102,  217,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  361,  360,  359,  358,  357,
      356,  355,  348,  348,  348,  354,  351,  350,  292,  218,
      347,  346,  345,  348,  348,  348,  348,  348,  348,   69,
       69,   69,   69,   69,   69,   69,   69,   69,  344,  205,
      343,  200,  340,  340,  338,   69,   69,   69,  168,  264,

      332,  331,  330,  329,  328,  327,   69,   69,   69,   69,
       69,   69,   69,   69,  326,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   74,  325,  324,
      323,  322,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,  111,  111,  111,  111,  111,  111,  111,  111,
      113,  113,  113,  113,  113,  113,  113,  113,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  181,  181,  321,  320,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  182,  318,
      182,  317,  316,  182,  182,  189,  189,  315,  314,  313,

      189,  193,  193,  193,  312,  193,  193,  216,  216,  311,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  219,  310,  309,  308,  307,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  247,  247,  247,
      306,  247,  247,  247,  261,  261,  305,  302,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  267,  301,  267,  267,  267,  300,
      297,  267,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  271,  296,  271,

      295,  271,  271,  271,  273,  273,  294,  292,  290,  273,
      278,  289,  288,  287,  278,  278,  278,  281,  281,  281,
      286,  281,  281,  281,  281,  319,  319,  319,  319,  319,
      319,  319,  319,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  335,  335,
      335,  205,  205,  335,  336,  336,  336,  284,  200,  336,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  339,  200,  282,  282,  339,
      339,  339,  349,  194,  349,  349,  349,  180,  268,  349,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  382,  382,  382,  168,  266,
      382,  264,  260,  382,  384,  384,  384,  259,  255,  384,
      254,  253,  384,  407,  407,  407,  250,  249,  407,  248,
      246,  407,  408,  408,  408,  245,  244,  408,  243,  242,
      408,  420,  420,  420,  241,  240,  420,  239,  238,  420,
      421,  421,  421,  237,  236,  421,  235,  234,  421,  430,
      430,  430,  233,  230,  430,  229,  228,  430,  431,  431,
      431,  227,  226,  431,  222,  221,  431,  436,  436,  436,
      220,  215,  436,  210,  209,  436,  437,  437,  437,  194,
      180,  437,  176,  175,  437,  174,  173,  172,  171,  168,

      159,  156,  155,  154,  136,  112,   75,   73,   72,   68,
      444,   59,    5,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444
    } ;

static const flex_int16_t yy_chk[1088] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,   11,    7,
        4,    7,    8,    9,    8,    9,   18,   19,   21,   23,
        3,    4,   39,   22,   23,   22,   39,   26,  440,   22,

       26,    3,    4,   28,   28,   29,   29,   23,   40,   18,
       19,   21,   21,   25,   11,   41,   25,   25,   30,   30,
       38,   40,   38,   22,   25,   46,   42,   38,   42,   43,
       57,   38,   42,   47,   41,   46,   25,   44,   42,   47,
       50,   43,   43,   44,   44,   25,   96,   96,   39,   44,
       18,   19,   21,   22,   24,   88,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   48,  439,   48,   51,   88,
       49,   57,   96,   24,   24,   62,   24,   24,   51,   64,
       62,   64,   24,   50,   24,   69,   49,   24,   24,   49,
      118,   24,   52,   62,  105,   52,   24,   60,   60,   60,

       60,   65,   24,   65,   52,   24,   61,   61,   61,   61,
       66,   52,   66,   67,   71,   67,   94,   97,   71,   97,
      128,   69,   71,   75,  128,  100,  118,   75,  100,   94,
       94,   71,  115,   94,  438,  105,   75,   98,   98,   98,
       98,   98,   98,   98,  101,  160,  101,  160,   97,  101,
      101,  102,  115,  102,   71,  116,  102,  102,  184,   75,
      150,  184,  437,   98,  122,  150,  161,  116,  161,   60,
       71,  436,  122,  122,   71,   75,   71,   71,   61,   75,
       71,   75,   75,  154,  162,   75,  162,  101,  154,  164,
      164,  164,  164,  180,  102,  182,  154,  183,  180,  183,

      186,  186,  189,  187,  187,  189,  197,  193,  182,  182,
      197,  202,  182,  225,  225,  202,  281,  160,  193,  271,
      216,  230,  262,  435,  262,  264,  186,  281,  183,  187,
      264,  230,  271,  271,  433,  186,  271,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  186,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  216,  273,  432,  431,
      273,  164,  166,  188,  191,  191,  191,  191,  191,  191,
      191,  278,  430,  190,  278,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  220,  429,  279,  428,  220,  279,
      191,  166,  166,  166,  427,  277,  277,  220,  166,  191,

      297,  425,  166,  166,  166,  166,  166,  166,  297,  421,
      191,  192,  192,  192,  192,  192,  192,  192,  218,  338,
      220,  277,  218,  420,  338,  339,  218,  381,  339,  418,
      277,  417,  381,  416,  414,  218,  220,  192,  413,  412,
      220,  277,  220,  411,  410,  408,  220,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  407,  406,  218,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  405,  404,
      402,  398,  395,  272,  218,  394,  389,  388,  218,  387,
      218,  386,  384,  382,  218,  274,  280,  280,  280,  280,
      280,  280,  280,  380,  378,  377,  375,  374,  373,  372,

      371,  370,  369,  368,  367,  366,  364,  363,  362,  360,
      359,  357,  280,  355,  353,  352,  349,  344,  343,  342,
      341,  280,  337,  336,  335,  333,  332,  331,  330,  329,
      328,  327,  280,  291,  325,  323,  322,  320,  317,  316,
      315,  313,  311,  310,  309,  308,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  307,  306,  305,  304,  303,
      300,  299,  291,  291,  291,  298,  295,  294,  293,  291,
      290,  289,  288,  291,  291,  291,  291,  291,  291,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  286,  285,
      284,  283,  276,  275,  269,  383,  383,  383,  267,  263,

      260,  259,  258,  257,  256,  255,  383,  383,  383,  383,
      383,  383,  445,  445,  254,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  446,  253,  252,
      251,  250,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  447,  447,  447,  447,  447,  447,  447,  447,
      448,  448,  448,  448,  448,  448,  448,  448,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  450,  450,  249,  248,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  451,  245,
      451,  244,  243,  451,  451,  452,  452,  242,  241,  240,

      452,  453,  453,  453,  239,  453,  453,  454,  454,  238,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  455,  237,  236,  235,  233,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  456,  456,  456,
      232,  456,  456,  456,  457,  457,  231,  229,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  459,  228,  459,  459,  459,  226,
      224,  459,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  461,  223,  461,

      222,  461,  461,  461,  462,  462,  221,  219,  215,  462,
      463,  214,  210,  208,  463,  463,  463,  464,  464,  464,
      206,  464,  464,  464,  464,  465,  465,  465,  465,  465,
      465,  465,  465,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  467,  467,
      467,  204,  203,  467,  468,  468,  468,  201,  199,  468,
      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  469,  469,  469,  469,  470,  198,  196,  195,  470,
      470,  470,  471,  194,  471,  471,  471,  179,  170,  471,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,

      472,  472,  472,  472,  472,  473,  473,  473,  169,  167,
      473,  165,  156,  473,  474,  474,  474,  155,  153,  474,
      152,  151,  474,  475,  475,  475,  149,  148,  475,  147,
      145,  475,  476,  476,  476,  144,  143,  476,  142,  141,
      476,  477,  477,  477,  140,  139,  477,  138,  137,  477,
      478,  478,  478,  136,  134,  478,  133,  131,  478,  479,
      479,  479,  129,  127,  479,  126,  125,  479,  480,  480,
      480,  124,  123,  480,  121,  120,  480,  481,  481,  481,
      119,  117,  481,  114,  110,  481,  482,  482,  482,   99,
       91,  482,   85,   82,  482,   81,   79,   78,   76,   74,

       59,   55,   54,   53,   45,   36,   15,   14,   13,   10,
        5,    2,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[146] =
    {   0,
0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 6 "lexer.l"
  #include <stdio.h>
  #include <stdlib.h>
  #include <string.h>
  #include "ast.h"
  #include "parser.tab.h"
  static char* dup_text(void){ size_t n=yyleng; char* s=(char*)malloc(n+1); memcpy(s,yytext,n); s[n]=0; return s; }
  #define RET(tok)  do{ return tok; }while(0)
  #define RETS(tok) do{ yylval.str=dup_text(); return tok; }while(0)
#line 880 "lex.yy.c"

#line 882 "lex.yy.c"

#define INITIAL 0
#define NLSEMI 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 32 "lexer.l"


#line 1106 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 445 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 444 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "lexer.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "lexer.l"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 37 "lexer.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lexer.l"
;
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 41 "lexer.l"
;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 42 "lexer.l"
{ BEGIN(INITIAL); RET(EOS); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 44 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 45 "lexer.l"
{ BEGIN(INITIAL); RET(EOS); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "lexer.l"
{ BEGIN(INITIAL); RET(EOS); }
	YY_BREAK
case YY_STATE_EOF(NLSEMI):
#line 47 "lexer.l"
{ BEGIN(INITIAL); RET(EOS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "lexer.l"
{ RET(ALIGN); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "lexer.l"
{ RET(AND); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "lexer.l"
{ BEGIN(NLSEMI); RET(ANY); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "lexer.l"
{ RET(AS); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "lexer.l"
{ RET(ASM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "lexer.l"
{ RET(ASYNC); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "lexer.l"
{ BEGIN(NLSEMI); RET(AWAIT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "lexer.l"
{ BEGIN(NLSEMI); RET(BREAK); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "lexer.l"
{ RET(CATCH); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "lexer.l"
{ RET(COMPTIME); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "lexer.l"
{ RET(CODE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "lexer.l"
{ RET(COMPLEX); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "lexer.l"
{ RET(CONST); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "lexer.l"
{ BEGIN(NLSEMI); RET(CONTINUE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "lexer.l"
{ RET(DYN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "lexer.l"
{ RET(DEFER); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "lexer.l"
{ RET(ELSE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "lexer.l"
{ RET(ENUM); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "lexer.l"
{ RET(ERRDEFER); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "lexer.l"
{ RET(ERROR); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "lexer.l"
{ RET(EXPORT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "lexer.l"
{ RET(EXTERN); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "lexer.l"
{ BEGIN(NLSEMI); RET(FALSE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "lexer.l"
{ RET(FN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "lexer.l"
{ RET(FOR); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "lexer.l"
{ RET(IF); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "lexer.l"
{ RET(IN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "lexer.l"
{ RET(IS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "lexer.l"
{ RET(INSERT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "lexer.l"
{ RET(IMPORT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "lexer.l"
{ RET(MATCH); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "lexer.l"
{ RET(MLIR); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "lexer.l"
{ BEGIN(NLSEMI); RET(NORETURN); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "lexer.l"
{ BEGIN(NLSEMI); RET(NULL_KW); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "lexer.l"
{ RET(OPAQUE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "lexer.l"
{ RET(OR); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "lexer.l"
{ RET(ORELSE); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "lexer.l"
{ RET(PACKAGE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "lexer.l"
{ RET(PROC); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "lexer.l"
{ RET(PUB); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "lexer.l"
{ BEGIN(NLSEMI); RET(RETURN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "lexer.l"
{ RET(LINKSECTION); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "lexer.l"
{ RET(SIMD); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "lexer.l"
{ RET(STRUCT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "lexer.l"
{ RET(THREADLOCAL); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "lexer.l"
{ RET(TENSOR); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "lexer.l"
{ RET(TEST); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "lexer.l"
{ BEGIN(NLSEMI); RET(TRUE); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "lexer.l"
{ RET(TYPE); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "lexer.l"
{ RET(TYPEOF); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "lexer.l"
{ RET(UNION); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "lexer.l"
{ BEGIN(NLSEMI); RET(UNDEFINED); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "lexer.l"
{ RET(UNREACHABLE); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 102 "lexer.l"
{ RET(VARIANT); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 103 "lexer.l"
{ RET(WHILE); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "lexer.l"
{ RET(UNDERSCORE); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "lexer.l"
{ BEGIN(NLSEMI); RETS(RAW_IDENTIFIER); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "lexer.l"
{ BEGIN(NLSEMI); RETS(NON_KEYWORD_IDENTIFIER); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "lexer.l"
{ BEGIN(NLSEMI); RETS(NON_KEYWORD_IDENTIFIER); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "lexer.l"
{ BEGIN(NLSEMI); RETS(CHAR_LITERAL); }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 111 "lexer.l"
{ BEGIN(NLSEMI); RETS(STRING_LITERAL); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "lexer.l"
{ BEGIN(NLSEMI); RETS(BYTE_LITERAL); }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 113 "lexer.l"
{ BEGIN(NLSEMI); RETS(BYTE_STRING_LITERAL); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "lexer.l"
{ BEGIN(NLSEMI); RETS(IMAGINARY_LITERAL); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "lexer.l"
{ BEGIN(NLSEMI); RETS(FLOAT_LITERAL); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 117 "lexer.l"
{ BEGIN(NLSEMI); RETS(FLOAT_LITERAL); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "lexer.l"
{ BEGIN(NLSEMI); RETS(INTEGER_LITERAL); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "lexer.l"
{ RET(SHLPIPEEQ); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "lexer.l"
{ RET(SHLPIPE); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "lexer.l"
{ RET(PLUSPIPEEQ); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "lexer.l"
{ RET(PLUSPIPE); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "lexer.l"
{ RET(MINUSPIPEEQ); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "lexer.l"
{ RET(MINUSPIPE); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "lexer.l"
{ RET(STARPIPEEQ); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "lexer.l"
{ RET(STARPIPE); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "lexer.l"
{ RET(PLUSPERCENTEQ); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "lexer.l"
{ RET(PLUSPERCENT); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "lexer.l"
{ RET(MINUSPERCENTEQ); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "lexer.l"
{ RET(MINUSPERCENT); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "lexer.l"
{ RET(STARPERCENTEQ); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 133 "lexer.l"
{ RET(STARPERCENT); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 135 "lexer.l"
{ RET(SHLEQ); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 136 "lexer.l"
{ RET(SHREQ); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 137 "lexer.l"
{ RET(PIPEPIPE); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 138 "lexer.l"
{ RET(EQEQ); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 139 "lexer.l"
{ RET(NE); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 140 "lexer.l"
{ RET(GE); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 141 "lexer.l"
{ RET(LE); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 142 "lexer.l"
{ RET(PLUSEQ); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 143 "lexer.l"
{ RET(MINUSEQ); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 144 "lexer.l"
{ RET(RARROW); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 145 "lexer.l"
{ RET(STAREQ); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 146 "lexer.l"
{ RET(SLASHEQ); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 147 "lexer.l"
{ RET(PERCENTEQ); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 148 "lexer.l"
{ RET(CARETEQ); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 149 "lexer.l"
{ RET(ANDEQ); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 150 "lexer.l"
{ RET(OREQ); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "lexer.l"
{ RET(DOTDOTEQ); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 153 "lexer.l"
{ RET(DOTDOTDOT); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 154 "lexer.l"
{ RET(DOTDOT); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 155 "lexer.l"
{ BEGIN(NLSEMI); RET(DOTSTAR); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 156 "lexer.l"
{ RET(DOTLPAREN); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 157 "lexer.l"
{ RET(DOTLSQUAREBRACKET); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 158 "lexer.l"
{ RET(DOTLCURLYBRACE); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 160 "lexer.l"
{ BEGIN(NLSEMI); RET(QUESTION); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 161 "lexer.l"
{ BEGIN(NLSEMI); RET(BANG); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 162 "lexer.l"
{ RET(LCURLYBRACE); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 163 "lexer.l"
{ BEGIN(NLSEMI); RET(RCURLYBRACE); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 164 "lexer.l"
{ RET(LSQUAREBRACKET); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 165 "lexer.l"
{ BEGIN(NLSEMI); RET(RSQUAREBRACKET); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 166 "lexer.l"
{ RET(LPAREN); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 167 "lexer.l"
{ BEGIN(NLSEMI); RET(RPAREN); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 168 "lexer.l"
{ RET(PLUS); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 169 "lexer.l"
{ RET(MINUS); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 170 "lexer.l"
{ RET(STAR); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 171 "lexer.l"
{ RET(SLASH); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 172 "lexer.l"
{ RET(PERCENT); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 173 "lexer.l"
{ RET(CARET); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 174 "lexer.l"
{ RET(B_AND); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 175 "lexer.l"
{ RET(B_OR); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 176 "lexer.l"
{ RET(SHL); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 177 "lexer.l"
{ RET(SHR); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 178 "lexer.l"
{ RET(EQ); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 179 "lexer.l"
{ RET(GT); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 180 "lexer.l"
{ RET(LT); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 181 "lexer.l"
{ RET(AT); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 182 "lexer.l"
{ RET(DOT); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 183 "lexer.l"
{ RET(COMMA); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 184 "lexer.l"
{ RET(SEMI); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 185 "lexer.l"
{ RET(COLON); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 186 "lexer.l"
{ RET(COLONCOLON); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 187 "lexer.l"
{ RET(COLONEQ); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 188 "lexer.l"
{ RET(FATARROW); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 189 "lexer.l"
{ RET(POUND); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 191 "lexer.l"
{ return 0; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 193 "lexer.l"
;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 195 "lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1910 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 445 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 445 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 444);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 195 "lexer.l"



